<? /** @var callable $path */?>

</div>

<footer class="footer text-center">
    <span class="hidden-md-down">Оптимизация складских процессов по размещению и сбору товаров на основе метода ветвей и границ</span>
    &copy; Романов Д.В. 2017
</footer>

<script src="<?= $path('vendor/twbs/bootstrap/docs/assets/js/vendor/jquery-slim.min.js') ?>"></script>
<script src="<?= $path('vendor/twbs/bootstrap/docs/assets/js/vendor/tether.min.js') ?>"></script>
<script src="<?= $path('vendor/twbs/bootstrap/dist/js/bootstrap.min.js') ?>"></script>

</body>
</html>