<? require_once realpath(__DIR__ . '/../../src/bootstrap.php') ?>
<? $path = function ($path) { return '/disser/' . $path; } ?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Магистерская диссертация</title>
    <link href="<?= $path('vendor/twbs/bootstrap/dist/css/bootstrap.min.css') ?>" rel="stylesheet">
    <link href="<?= $path('vendor/components/font-awesome/css/font-awesome.min.css') ?>" rel="stylesheet">
    <link href="<?= $path('web/css/sticky-footer.css') ?>" rel="stylesheet">
</head>
<body style="padding-top:5rem">

<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="fa fa-bank"></i> СКЛАД</a>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-dropbox"></i> Товары</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-cart-arrow-down"></i> Сбор</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-gears"></i> Настройки</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" title="Выйти"><i class="fa fa-sign-out"></i> Калинина К.А.</button>
        </form>
    </div>
</nav>

<div class="container">