<? require_once 'layout/header.phtml' ?>

<div class="jumbotron">
    <h1 class="display-3">Магистерская диссертация</h1>
    <p class="lead">Оптимизация складских процессов по размещению и сбору товаров на основе метода ветвей и границ</p>
    <hr class="my-4">
    <p>Романов Д.В., ИПм-151. Руководитель: Рындин А.А.</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="product_list.phtml" role="button">Приступить к работе</a>
    </p>
</div>

<? require_once 'layout/footer.phtml' ?>
