<? require_once 'layout/header.phtml' ?>
<? /** @var array $config */?>

<div class="row">
    <div class="col-lg-9 form-group">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Наименование, штрих-код, ячейка...">
            <span class="input-group-btn">
                <button class="btn btn-secondary" type="button"><i class="fa fa-search"></i> Поиск</button>
            </span>
        </div>
    </div>
    <div class="col-lg-3 form-group">
        <a href="product_add.phtml" class="btn btn-outline-success btn-block"><i class="fa fa-plus"></i> Добавить новый</a>
    </div>
</div>

<ul class="nav nav-tabs" style="margin-bottom:-1px">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#t1">Ожидают размещения <span class="badge badge-pill badge-default">216</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#t2">На складе <span class="badge badge-pill badge-primary">53</span></a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="t1">
        <table class="table">
            <thead>
            <tr>
                <th>Товар</th>
                <th>Штрих-код</th>
                <th>Габариты</th>
                <th>Тип</th>
                <th>Дата прибытия</th>
                <th>Ячейка</th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($config['goods'] as $product): ?>
                <? $product = (object) $product ?>
                <tr>
                    <td><?= $product->name ?></td>
                    <td><a href="product_edit.phtml"><?= $product->barcode ?></a></td>
                    <td><?= "{$product->dimension_x}&times;{$product->dimension_y}&times;{$product->dimension_z} см, {$product->weight} г" ?></td>
                    <td><?= $config['product_types'][$product->type] ?></td>
                    <td><?= DateTime::createFromFormat('Y-m-d', $product->add_date)->format('d.m.Y') ?></td>
                    <td>
                        <div class="input-group">
                            <select class="form-control custom-select">
                                <? foreach ($config['cells'] as $cell): ?>
                                    <option><?= $cell ?></option>
                                <? endforeach ?>
                            </select>
                            <span class="input-group-btn">
                        <button class="btn btn-secondary" type="button"> Присвоить</button>
                    </span>
                        </div>
                    </td>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="tab-pane" id="t2">
        <table class="table">
            <thead>
            <tr>
                <th>Товар</th>
                <th>Штрих-код</th>
                <th>Габариты</th>
                <th>Тип</th>
                <th>Ячейка</th>
                <th>Дата прибытия</th>
                <th>Дата размещения</th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($config['goods'] as $product): ?>
                <? $product = (object) $product ?>
                <tr>
                    <td><?= $product->name ?></td>
                    <td><a href="product_edit.phtml"><?= $product->barcode ?></a></td>
                    <td><?= "{$product->dimension_x}&times;{$product->dimension_y}&times;{$product->dimension_z} см, {$product->weight} г" ?></td>
                    <td><?= $config['product_types'][$product->type] ?></td>
                    <td><span class="badge badge-default"><?= $product->cell ?></span></td>
                    <td><?= DateTime::createFromFormat('Y-m-d', $product->add_date)->format('d.m.Y') ?></td>
                    <td><?= DateTime::createFromFormat('Y-m-d', $product->locate_date)->format('d.m.Y') ?></td>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
</div>

<nav>
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="#">
                <span>&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link" href="#">
                <span>&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

<? require_once 'layout/footer.phtml' ?>
