<? require_once 'layout/header.phtml' ?>
<? /** @var array $config */?>

<div class="row">
    <div class="col-lg-9 form-group">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="ФИО">
            <span class="input-group-btn">
                <button class="btn btn-secondary" type="button"><i class="fa fa-search"></i> Поиск</button>
            </span>
        </div>
    </div>
    <div class="col-lg-3 form-group">
        <a href="product_add.phtml" class="btn btn-outline-success btn-block"><i class="fa fa-plus"></i> Добавить нового</a>
    </div>
</div>

<ul class="nav nav-tabs" style="margin-bottom:-1px">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#t1">Действующие <span class="badge badge-pill badge-default">31</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#t2">Уволенные <span class="badge badge-pill badge-default">6</span></a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="t1">
        <table class="table">
            <thead>
            <tr>
                <th>ФИО</th>
                <th>Должность</th>
                <th>Дата начала работы</th>
                <th width="1%"></th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($config['employees'] as $employee): ?>
                <? $employee = (object) $employee ?>
                <tr>
                    <td><?= $employee->name ?></td>
                    <td><?= $employee->function ?></td>
                    <td><?= DateTime::createFromFormat('Y-m-d', $employee->hiring_date)->format('d.m.Y') ?></td>
                    <td class="text-nowrap">
                        <a href="#" class="btn btn-secondary"><i class="fa fa-calendar"></i> Статистика</a>
                        <a href="#" class="btn btn-outline-primary"><i class="fa fa-edit"></i> Редактировать</a>
                        <a href="#" class="btn btn-outline-danger"><i class="fa fa-times"></i> Уволить</a>
                    </td>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="tab-pane" id="t2">
        ...
    </div>
</div>

<nav>
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="#">
                <span>&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item">
            <a class="page-link" href="#">
                <span>&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

<? require_once 'layout/footer.phtml' ?>
